title: Active Directory Project
description: In this project, we immitate the scenario of an entreprise hosting their splunk server for the cybersecurity team on a ubuntu server environment. The goal of this project is to analyze data forwarded from different computers (via Splunk Universal Forwarder) that joined the entreprise's active directory
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
